# Generated by Django 4.1.7 on 2023-05-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireAlertServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map_url', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=350)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('incident_type', models.CharField(choices=[('sample', 'Sample'), ('test', 'Test')], default='sample', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/services/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/services/')),
                ('is_done', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_profille', to='user_profile.userprofile')),
            ],
        ),
    ]
