# Generated by Django 4.1.7 on 2023-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_guard', '0002_firealertservices_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealertservices',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='firealertservices',
            name='incident_type',
            field=models.CharField(choices=[('FIRE_INCIDENT', 'Fire Incidents'), ('VEHICULAR_ACCIDENT', 'Vehicular Accidents'), ('NATURAL_CALAMITIES', 'Natural Calamities'), ('OTHERS', 'Others')], default='OTHERS', max_length=100),
        ),
    ]
