# Generated by Django 4.1.7 on 2023-08-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_guard', '0003_firealertservices_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealertservices',
            name='travel_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='firealertservices',
            name='google_map_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
