# Generated by Django 4.1.7 on 2023-05-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='user',
        ),
    ]
