# Generated by Django 4.2 on 2023-04-30 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=25)),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='front-pictures/')),
                ('back_photo', models.ImageField(blank=True, null=True, upload_to='back-pictures/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('max_otp_try', models.CharField(default=5, max_length=2)),
                ('otp_max_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
